### ISSUE TITLE
More Documentation

### ISSUE THREAD

**Issue by nicholas-leonard** [ludc/rltorch#1]
Hi @ludc,

Do you think you could add reference markdown documentation for the main classes of the rltorch library? That would give this package an additional edge over the competition.

BTW, this package is great. Thanks a million for taking the time to make it so great :)

**Comment by ludc** [comment]
Yes, let me a few days.....

 Thank you

 Ludovic

**Comment by ludc** [comment]
Hi again,

I have updated the documentation and I now provide more explanations about the implementation of the different classes..... It is not well written, but it gives an overview of this package.

**Comment by nicholas-leonard** [comment]
@ludc That was fast! It is looking much better. Now if only we had a nice complete tutorial in markdown :)

**Comment by ludc** [comment]
Done... (at least a partial one)
